version: "3"
services:
  postgres:
    image: postgres:10.4
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

# open docker shell:
# $ docker ps
#   get the container id
# $ docker exec -it <container id goes here> bash

# to rebuild everything
# $ docker-compose down
# $ docker-compose up --force-recreate --build
#
# DATABASE_URL: postgres://user:pass@postgres:5432/db